/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        FindNumberOfBuses findNumberOfBuses = new FindNumberOfBuses();
        findNumberOfBuses.runRedbusTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        System.out.println(new App().getGreeting());
    }
}
